// Publication and preprint context. Keep claims conservative and source-backed.
// Deliberately terse: this block is resent on every turn, so prose beyond what a
// visitor needs in order to decide whether to open the paper is paid for on every
// message. Author lists stay in full — they answer real questions and compress badly.
export const PUBLICATIONS_CONTEXT = `Publications and preprints:
- "UnpredictaBench: A Benchmark for Evaluating Distributional Randomness in LLMs" (2026 arXiv preprint) with Amirhossein Abaskohi, Liang Luo, Ellie Dingqiao Wen, Lele Wang, Giuseppe Carenini, and Peter West; Abaskohi and Dabiriaghdam contributed equally. Tests whether LLMs sample from true target distributions rather than merely producing diverse plausible answers, over 448 problems spanning statistical distributions, stochastic programs and language-based random processes. Introduces KS@N, based on the Kolmogorov-Smirnov test; no model exceeds 40%, and reasoning helps but does not solve it.
- "VAMPS: Visual-Assisted Mathematical Problem Solving Benchmark" (2026 arXiv preprint) with Shayan Vassef, Mohammadreza Bakhtiari, Yasamin Medghalchi, Ilker Hacihaliloglu, Mesrob Ohannessian, Lele Wang, and Giuseppe Carenini. Asks whether multimodal LLMs can build a useful graph and reason from it, over 1,168 bilingual multiple-choice pairs from Iranian University Entrance Exam algebra and calculus questions plus reviewed synthetic variants. Direct analytical solving unexpectedly outperforms tool-enabled visual solving.
- "When Minor Edits Matter: LLM-Driven Prompt Attack for Medical VLM Robustness in Ultrasound" (2026 arXiv preprint) with Yasamin Medghalchi, Milad Yazdani, Moein Heidari, Mojan Izadkhah, Zahra Kavian, Giuseppe Carenini, Lele Wang, Dena Shahriari, and Ilker Hacihaliloglu. Evaluates medical vision-language models under clinically plausible prompt variations in ultrasound question answering (LLM-generated rewrites and minimal edits such as typos, shorthand and underspecified wording), reporting robustness gaps relevant to safe clinical use.
- "SimMark: A robust sentence-level similarity-based watermarking algorithm for large language models" (EMNLP 2025 oral) with Lele Wang. A sentence-level watermark for LLM outputs needing no model internals, so it works with black-box or API-accessed models. It uses semantic sentence embeddings and rejection sampling to create a statistically detectable pattern while aiming to preserve perceived quality and fluency; detection compares neighbouring sentence embeddings with a soft-counting statistical test. Reported: robustness to paraphrasing, sampling efficiency and cross-domain applicability.
- "SOI Matters: Analyzing Multi-Setting Training Dynamics in Pretrained Language Models via Subsets of Interest" (MRL 2025, with EMNLP 2025) with Shayan Vassef, Mohammadreza Bakhtiari, and Yadollah Yaghoobzadeh. Introduces Subsets of Interest (SOI), six learning-behaviour categories (e.g. forgettable, unlearned, always-correct) tracked across multi-task, multi-source and multilingual training. Multi-source learning improves out-of-distribution performance by up to 7%; multi-task results are mixed. Two-stage fine-tuning selecting subsets via SOI gives further gains.
- "BcAmirs at SemEval-2024 Task 4: Beyond words: A multimodal and multilingual exploration of persuasion in memes" (SemEval 2024, with NAACL 2024) with Amirhossein Abaskohi, Lele Wang, and Giuseppe Carenini. Hierarchical multi-label classification of persuasion techniques in memes, adding generated image captions to narrow the visual-textual gap, with RoBERTa and CLIP encoders. Beat the baseline on all 12 subtasks: top three for Subtask 2a, top four for 2b.
- "Targeted Adversarial Attacks Against Neural Machine Translation" (ICASSP 2023) with Sahar Sadrizadeh, Ljiljana Dolamic, and Pascal Frossard. Makes small, meaning-preserving edits to a source sentence so an NMT system inserts a predefined keyword, via gradient projection in embedding space. Reports keyword insertion in over 75% of sentences while preserving source similarity.`;
